/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "utils_defs.h"
#include "hal_gpio.h"
#include "hal_spi.h"

void delay(void)
{
	uint32_t i;

	for(i = 0; i < 500000/4; i++);
}

int main(void)
{
	GPIO_Handle_t LedPin = {0};

	GPIO_EnableClock(GPIOC);

	/* Set Led Pin Configuration */
	LedPin.pGPIOx = GPIOC;
	LedPin.Number = GPIO_PIN_13;
	LedPin.Mode = GPIO_OUT_PUSH_PULL;
	LedPin.Speed = GPIO_SPEED_MEDIUM;

	GPIO_InitPin(&LedPin);

    /* Loop forever */
	for(;;)
	{
		GPIO_Toggle(LedPin.pGPIOx, LedPin.Number);
		delay();
	}
}

